name: Update IaC Submodule

on:
  repository_dispatch:
    types: [update-iac]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Update IaC submodule
        run: |
          cd dev-link-iac
          git pull origin main
          cd ..

      - name: Commit submodule update
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"

          git add dev-link-iac
          git commit -m "chore: bump dev-link-iac to  ${{ github.event.client_payload.version }}"
          git push
